version: "3.6"

# add --appendonly -yes flag to REDIS_ARGS as replacement for better persistence management
services:
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    restart: unless-stopped
    environment:
       REDIS_ARGS: --save 60 1
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

  db:
    build: $HOME/Documents/musala-logistics-roughsheet/db
    ports:
      - 1433:1433

#  musala-logistics:
#    depends_on:
#      - redis
#      - mssql-server
#    build: ./Users/osobu/Documents/musala-logistics-roughsheet
#    restart: on-failure
#    env_file: ./.env
#    ports:
#      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#    environment:
#      SPRING_APPLICATION_JSON: '{
#          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#          "spring.datasource.username" : "$MYSQLDB_USER",
#          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#          "spring.jpa.hibernate.ddl-auto" : "update"
#        }'
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true

volumes:
  redis_data: