version: "3.6"

# add --appendonly -yes flag to REDIS_ARGS as replacement for better persistence management
services:
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    environment:
       REDIS_ARGS: --save 60 1
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

volumes:
  redis_data: