insert into Medication (name, weight, code, created, delivered)values ('ade123', 420, 'ade123', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade124', 200, 'ade124', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade125', 220, 'ade125', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade126', 145, 'ade126', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade127', 132, 'ade127', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade128', 190, 'ade128', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade129', 65, 'ade129', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade130', 32, 'ade130', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade131', 45, 'ade131', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade132', 65, 'ade132', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade133', 76, 'ade133', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade134', 67, 'ade134', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade135', 67, 'ade135', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade136', 89, 'ade136', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade137', 234, 'ade137', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade138', 136, 'ade138', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade139', 55, 'ade139', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade140', 255, 'ade140', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade141', 300, 'ade141', getDate(), 0)
insert into Medication (name, weight, code, created, delivered)values ('ade142', 180, 'ade142', getDate(), 0)


insert into users(email, password, role, enabled, created, creator, updater, username) values ('aosobu.dev@gmail.com', '$2a$10$AA43KvvSlI0lj3OzVIL0/.jRNkmvR7SmAGPIba5YUGunibYOak6.y', 'USER', 1, getDate(), 'system_user', 'system_user','aosobu.dev' )